name: Build ImmortalWrt kmods

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ImmortalWrt
        uses: actions/checkout@v4
        with:
          repository: immortalwrt/immortalwrt
          ref: openwrt-24.10

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib gettext git libncurses-dev libssl-dev \
          python3 python3-distutils rsync unzip zlib1g-dev file wget

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure target and kmods
        run: |
          echo "CONFIG_TARGET_ramips=y" > .config
          echo "CONFIG_TARGET_ramips_mt7621=y" >> .config
          echo "CONFIG_PACKAGE_kmod-inet-diag=m" >> .config
          echo "CONFIG_PACKAGE_kmod-netlink-diag=m" >> .config
          echo "CONFIG_PACKAGE_kmod-tun=m" >> .config
          make defconfig

      - name: Build kernel modules
        run: |
          make package/kmod-inet-diag/compile -j$(nproc)
          make package/kmod-netlink-diag/compile -j$(nproc)
          make package/kmod-tun/compile -j$(nproc)

      - name: Upload kmod ipks
        uses: actions/upload-artifact@v4
        with:
          name: kmods-ipk
          path: bin/targets/ramips/mt7621/packages/*.ipk
